version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: node-app
    command: bash -c "npm run start"
    container_name: node-app
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    